/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Account } from './account';
import { PostUser } from './postUser';
import { Tag } from './tag';
import { Version } from './version';

export class Post {
    'id'?: number;
    'uuid'?: string;
    'status'?: string;
    'accounts'?: Array<Account>;
    'versions'?: Array<Version>;
    'tags'?: Array<Tag>;
    'user'?: PostUser;
    'scheduledAt'?: string;
    'publishedAt'?: string;
    'createdAt'?: string;
    'trashed'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<Account>"
        },
        {
            "name": "versions",
            "baseName": "versions",
            "type": "Array<Version>"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<Tag>"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "PostUser"
        },
        {
            "name": "scheduledAt",
            "baseName": "scheduled_at",
            "type": "string"
        },
        {
            "name": "publishedAt",
            "baseName": "published_at",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "trashed",
            "baseName": "trashed",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Post.attributeTypeMap;
    }
}

