/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { VersionOptionsTiktokPrivacyLevel } from './versionOptionsTiktokPrivacyLevel';

export class VersionOptionsTiktok {
    'privacyLevel'?: VersionOptionsTiktokPrivacyLevel;
    'allowComments'?: VersionOptionsTiktokPrivacyLevel;
    'allowDuet'?: VersionOptionsTiktokPrivacyLevel;
    'allowStitch'?: VersionOptionsTiktokPrivacyLevel;
    'contentDisclosure'?: VersionOptionsTiktokPrivacyLevel;
    'brandOrganicToggle'?: VersionOptionsTiktokPrivacyLevel;
    'brandContentToggle'?: VersionOptionsTiktokPrivacyLevel;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "privacyLevel",
            "baseName": "privacy_level",
            "type": "VersionOptionsTiktokPrivacyLevel"
        },
        {
            "name": "allowComments",
            "baseName": "allow_comments",
            "type": "VersionOptionsTiktokPrivacyLevel"
        },
        {
            "name": "allowDuet",
            "baseName": "allow_duet",
            "type": "VersionOptionsTiktokPrivacyLevel"
        },
        {
            "name": "allowStitch",
            "baseName": "allow_stitch",
            "type": "VersionOptionsTiktokPrivacyLevel"
        },
        {
            "name": "contentDisclosure",
            "baseName": "content_disclosure",
            "type": "VersionOptionsTiktokPrivacyLevel"
        },
        {
            "name": "brandOrganicToggle",
            "baseName": "brand_organic_toggle",
            "type": "VersionOptionsTiktokPrivacyLevel"
        },
        {
            "name": "brandContentToggle",
            "baseName": "brand_content_toggle",
            "type": "VersionOptionsTiktokPrivacyLevel"
        }    ];

    static getAttributeTypeMap() {
        return VersionOptionsTiktok.attributeTypeMap;
    }
}

