/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { VersionOptionsInstagram } from './versionOptionsInstagram';
import { VersionOptionsLinkedin } from './versionOptionsLinkedin';
import { VersionOptionsMastodon } from './versionOptionsMastodon';
import { VersionOptionsPinterest } from './versionOptionsPinterest';
import { VersionOptionsTiktok } from './versionOptionsTiktok';
import { VersionOptionsYoutube } from './versionOptionsYoutube';

export class VersionOptions {
    'tiktok'?: VersionOptionsTiktok;
    'youtube'?: VersionOptionsYoutube;
    'linkedin'?: VersionOptionsLinkedin;
    'mastodon'?: VersionOptionsMastodon;
    'instagram'?: VersionOptionsInstagram;
    'pinterest'?: VersionOptionsPinterest;
    'facebookPage'?: VersionOptionsInstagram;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tiktok",
            "baseName": "tiktok",
            "type": "VersionOptionsTiktok"
        },
        {
            "name": "youtube",
            "baseName": "youtube",
            "type": "VersionOptionsYoutube"
        },
        {
            "name": "linkedin",
            "baseName": "linkedin",
            "type": "VersionOptionsLinkedin"
        },
        {
            "name": "mastodon",
            "baseName": "mastodon",
            "type": "VersionOptionsMastodon"
        },
        {
            "name": "instagram",
            "baseName": "instagram",
            "type": "VersionOptionsInstagram"
        },
        {
            "name": "pinterest",
            "baseName": "pinterest",
            "type": "VersionOptionsPinterest"
        },
        {
            "name": "facebookPage",
            "baseName": "facebook_page",
            "type": "VersionOptionsInstagram"
        }    ];

    static getAttributeTypeMap() {
        return VersionOptions.attributeTypeMap;
    }
}

