/**
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { VersionContent } from './versionContent';
import { VersionOptions } from './versionOptions';

export class Version {
    'accountId': number;
    'isOriginal': boolean;
    'content': VersionContent;
    'options'?: VersionOptions;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountId",
            "baseName": "account_id",
            "type": "number"
        },
        {
            "name": "isOriginal",
            "baseName": "is_original",
            "type": "boolean"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "VersionContent"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "VersionOptions"
        }    ];

    static getAttributeTypeMap() {
        return Version.attributeTypeMap;
    }
}

